# Adding in scheduler for 5:15am daily so that games can finish and it will start adding in new data/models/predictions at the beginning of the day.
name: Run Python Scripts

on:
  push:
    branches: [ main ]
  schedule:
    # Every day at 5:15 AM EST (which is 10:15 AM UTC)
    - cron: '21 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create log files if they do not exist
      run: |
        mkdir -p log
        touch log/success_log.txt
        touch log/error_log.txt

    # Rest of your steps for running notebooks and logging results...
  
    - name: Upload error log to GitHub
      if: ${{ failure() }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<your-bot-email@example.com>"
        git add log/error_log.txt
        git commit -m "Add error log" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Upload success log to GitHub
      if: ${{ success() }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<your-bot-email@example.com>"
        git add log/success_log.txt
        git commit -m "Add success log" || echo "No changes to commit"
        git push || echo "No changes to push"
